TP_Proekt_Rezervacii/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name="home_page"),
    path('contact', views.contact_page, name="contact_page"),
    path('accounts/', include('accounts.urls')),
    path('shops/', include('shops.urls')),
    path('appointments/', include('appointments.urls')),
    path('packages/', views.packages_page, name='packages_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shops_page, name='shops_page'),
    path('shop/<int:id>', views.shop_details_page, name='shop_details_page'),
]

shops/models.py
from django.db import models
from accounts.models import Account


class Shop(models.Model):
    name = models.CharField(max_length=200, blank=False)
    description = models.TextField(max_length=250, blank=True, default='')
    location = models.CharField(max_length=150, blank=False, default='')
    location_link = models.CharField(max_length=150, blank=False, default='',
                                     help_text='Google Maps link')
    logo = models.ImageField(upload_to='shop_logos', default='default.jpg', blank=True)
    owner = models.ForeignKey(Account, on_delete=models.CASCADE)

    def time_in_range(self, time, begin, end):
        if begin < time < end:
            return True
        return False

    def working_week_days(self):
        working_times = self.workingtime_set.all()
        working_days = [wt.day for wt in working_times if wt.opens != wt.closes]
        return working_days

    def open_close_time_by_weekday(self, weekday):
        working_day = self.workingtime_set.get(day=weekday)
        return working_day.opens, working_day.closes

    def timeslot_is_free(self, date, start, end):
        appointments = self.appointment_set.filter(date=date)

        for appt in appointments:
            if (self.time_in_range(start, appt.start_time, appt.end_time) or
                    self.time_in_range(end, appt.start_time, appt.end_time)):
                return False

            if start == appt.start_time or end == appt.end_time:
                return False
            # ako terminot preklopuva drug termin
            if start < appt.start_time and appt.end_time < end:
                return False

        return True

    def __str__(self):
        return self.name

workingtimes/models.py
from django.db import models
from shops.models import Shop


class WorkingTime(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    WEEKDAYS = [
        (1, "Monday"),
        (2, "Tuesday"),
        (3, "Wednesday"),
        (4, "Thursday"),
        (5, "Friday"),
        (6, "Saturday"),
        (7, "Sunday"),
    ]
    day = models.IntegerField(choices=WEEKDAYS, blank=False)
    opens = models.TimeField(default='09:00:00', blank=False, help_text='Example: 09:00:00')
    closes = models.TimeField(default='23:00:00', blank=False, help_text='Example: 23:59:00')

    class Meta:
        ordering = ('day', 'opens')

    def __str__(self):
        return f'{self.day}\t {self.opens}\t {self.closes}'

shops/views.py
from django.shortcuts import render
from .models import Shop
from workingtimes.models import WorkingTime
from services.models import Service


def shops_page(request):
    context = {'shops': Shop.objects.all()}
    return render(request, 'shops/partners.html', context)


def shop_details_page(request, id):
    shop = Shop.objects.get(id=id)
    times = WorkingTime.objects.filter(shop=shop)
    services = Service.objects.filter(shop=shop)
    context = {'shop': shop, 'times': times, 'services': services}
    return render(request, 'shops/shop_details.html', context)

templates/shops/partners.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Cards Business -->
<div class="container">
    <br>
  <div class="row row-cols-1 row-cols-md-4 g-4">
      {% for shop in shops %}
            <div class="col">
              <div class="card h-100">
                <img src="{{ shop.logo.url }}" class="card-img-top" alt="..." style="height: 250px">
                <div class="card-body">
                  <h3 class="card-title">{{ shop.name }}</h3>
                    <small>{{ shop.description }}</small>
                    <br>
                    <hr>
                  <a class="btn btn-primary" href="{% url 'shop_details_page' shop.id %}" role="button">Check Offers</a>
                </div>
              </div>
            </div>
      {% endfor %}
  </div>
<hr>
</div>
{% endblock content %}

templates/shops/shop_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
        <!-- Shop Header -->
        <!-- Shop Photo -->
        <br>
        <img src="{{ shop.logo.url }}" alt="Hairstyle Shop" class="img-fluid shop-photo">
        <div class="shop-header">
            <h1>{{ shop.name }}</h1>
        </div>
         <!-- Description -->
            <p>
                {{ shop.description }}
            </p>
        <!-- Address -->
            <p>
                <small>Address: </small>{{ shop.location }}
            </p>
            <p>
                📌<a href="{{ shop.location_link }}">{{ shop.location_link|truncatechars:64 }}</a>
            </p>
        <hr>
        <!-- Services with Prices -->
        <div class="services">
            <h2 style="text-align: center;">Services & Prices</h2>
            {% if services %}
                <table class="table">
                <tr>
                    <th>Service</th>
                    <th>Time to complete</th>
                    <th>Price</th>
                </tr>
                {% for serv in services %}
                    <tr>
                        <td>{{ serv.service }}</td>
                        <td>{{ serv.time_to_complete|time:"H:i" }}</td>
                        <td>{{ serv.price }}</td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <h4>Nothing to show right now</h4>
            {% endif %}
        </div>
        <br>
        <hr>
        <!-- Working Hours -->
        <div class="working-hours">
            <h2 style="text-align: center;">Working Hours</h2>
            {% if times %}
                <table class="table">
                <tr>
                    <th>Day</th>
                    <th>Opening Time</th>
                    <th>Closing Time</th>
                </tr>
                {% for day in times %}
                    {% if day.opens != day.closes %}
                        <tr>
                            <td>{{ day.get_day_display }}</td>
                            <td>{{ day.opens|date:"H:i"  }}</td>
                            <td>{{ day.closes|date:"H:i"  }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td>{{ day.get_day_display }}</td>
                            <td>-</td>
                            <td>-</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                <!-- Add more days and times as needed -->
            </table>
            {% else %}
                <h4>Nothing to show right now</h4>
            {% endif %}
        </div>
        <br>
        {% if services %}
            <div class="text-center py-4">
                <a href="{% url 'book_appointment_page' shop.id %}" class="btn btn-primary">Book now</a>
            </div>
        {% endif %}
    <hr>
    </div>
{% endblock content %}